# Generated by Django 2.1.1 on 2018-09-20 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.CharField(max_length=128, unique=True)),
                ('target_model', models.CharField(max_length=128)),
                ('inserted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'table_updates',
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('ts', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'task_events',
                'default_related_name': 'events',
            },
        ),
        migrations.CreateModel(
            name='TaskParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'task_parameters',
                'default_related_name': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('host', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tasks',
                'default_related_name': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='taskparameter',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='django_luigi.TaskRecord'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='django_luigi.TaskRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='taskparameter',
            unique_together={('task', 'name')},
        ),
    ]
