# Generated by Django 2.1.1 on 2018-09-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_luigi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskevent',
            name='event_name',
        ),
        migrations.AddField(
            model_name='taskevent',
            name='name',
            field=models.CharField(default='hey', editable=False, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='namespace',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='django_luigi.TaskRecord'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='taskparameter',
            name='name',
            field=models.CharField(db_index=True, editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='taskparameter',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='django_luigi.TaskRecord'),
        ),
        migrations.AlterField(
            model_name='taskparameter',
            name='value',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='host',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='name',
            field=models.CharField(db_index=True, editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='task_id',
            field=models.CharField(db_index=True, editable=False, max_length=200, unique=True),
        ),
    ]
