version: '2'

services:
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  server:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: server
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py makemigrations &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  jupyter:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: server
    command: >
      bash -c "./manage.py shell_plus --notebook"
    volumes:
      - ./:/code
    ports:
      - "8888:8888"
    depends_on:
      - server
  luigid:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_SETTINGS_MODULE=django_luigi.settings
    image: server
    command:
      - django-luigid
    volumes:
      - ./:/code
    ports:
      - "8082:8082"
    depends_on:
      - server

volumes:
  pgdata:
